### ISSUE TITLE
Lost UnityEditor.Editor import reference on install

### ISSUE THREAD

**Issue by exejutable** [AbZorbaGames/artificetoolkit#3]
I have my project with some custom editors and some plugins like `easy save 3`, when I add this library to my projects, I lose the reference of `Editor` in all the imports forcing me to change `Editor` to `UnityEditor.Editor`. Any suggestion ?

```
Type name expected, but namespace name found.
Namespace 'Editor' is declared in the following referenced assemblies:
abzorba.artificetoolkit.editor 0.0.0.0
```

my class before:

```
  public abstract class RecursiveEditor : Editor{}
```

and now to use Editor I need to change all my imports to this (I don't want to change the imports in all the code):

```
  public abstract class RecursiveEditor : UnityEditor.Editor{}
```

Extra information:

Unity Version: 2022.3.24f1

this can be a problem for all the projects using `Editor`

**Comment by ZackPer** [comment]
Hello @exejutable . Thanks for the issue! 

It was indeed caused by a wrong namespace convention I left from the previous branch. I forgot to change the original namespace provided by Rider which was not smart of me :) 

It should work now without conflicts. Can you confirm?

**Comment by exejutable** [comment]
Sorry for the delay, yes is working properly. Another question how can use this library with a `EditorWindow` ?

**Comment by ZackPer** [comment]
Hello @exejutable 

All good no worries. 

There are two ways I can interpret your question. One is using ArtificeDrawer as a first class citizen, inside your own EditorWindow. Or, use the ArtificeWindow to let it create the contents of the window on its own. I assume you want the second option so use the following steps:

1. Create a .cs script in your project inside of an Editor folder.
2. Inherit from the ArtificeWindow class
3. Add a static method to be able to open the window through the menu item as seen here in the [ShowExample](https://docs.unity3d.com/6000.0/Documentation/ScriptReference/EditorWindow.html) method
4. Add fields into your script as if its a MonoBehaviour and they should be showing in the window!

You can use the [Button] attribute and the [OnValueChanged] for intractability.

Hope this helps!

**Comment by exejutable** [comment]
Works, i create a example.


<details>
<summary>Example</summary>

```c#
public abstract class SelectAssetWindowEditor<T>: EditorWindow where T: ScriptableObject
{
    private T template;
    private VisualElement scrollElement;
    private const string PERSIST_KEY = "TemplatePath";
    private ArtificeDrawer artificeDrawer;
    private ObjectField objectField;
    protected abstract string FolderPath { get; }

    private void OnEnable()
    {
        Undo.undoRedoPerformed += SaveOnUndoRedo;

        if (EditorPrefs.HasKey(PERSIST_KEY))
        {
            string path = EditorPrefs.GetString(PERSIST_KEY);
            template = AssetDatabase.LoadAssetAtPath<T>(path);
        }
    }

    private void OnDisable()
    {
        Undo.undoRedoPerformed -= SaveOnUndoRedo;
    }

    private void SaveOnUndoRedo()
    {
        if (template != null)
            Forms.SaveAsset(template);
    }

    protected  void CreateGUI()
    {
        VisualElement horizontalContainer = new VisualElement
        {
            style = {
                flexDirection = FlexDirection.Row,
                minHeight = 20,
            },
        };

        horizontalContainer.AddToClassList("horizontal-container");

        objectField = new ObjectField("Asset")
        {
            objectType = typeof(T),
            value = template,
            style =
            {
                width = 340,
            }
        };

        objectField.RegisterValueChangedCallback(evt =>
        {
            template = (T)evt.newValue;
            DrawElement(template);
            if (template != null)
            {
                string path = AssetDatabase.GetAssetPath(template);
                EditorPrefs.SetString(PERSIST_KEY, path);
            }
        });

        horizontalContainer.Add(objectField);

        Button createAsset = new Button(CreateNewAsset)
        {
            text = "New",
            style = {
                width = 50,
            },
        };
        Button createAssetAndLoad = new Button(CreateAndLoadAsset)
        {
            text = "New & Load",
            style = {
                width = 100,
            },
        };

        horizontalContainer.Add(createAsset);
        horizontalContainer.Add(createAssetAndLoad);

        VisualElement flexibleSpace = new VisualElement
        {
            style = {
                flexGrow = 1,
            },
        };

        horizontalContainer.Add(flexibleSpace);

        rootVisualElement.Add(horizontalContainer);

        scrollElement = new ScrollView();
        scrollElement.styleSheets.Add(Artifice_Utilities.GetStyle(typeof(ArtificeEditorWindow)));
        scrollElement.AddToClassList("root-visual-element");
        rootVisualElement.Add(scrollElement);

        if(template != null)
        {
            DrawElement(template);
        }
    }

    private void DrawElement(Object activeObject)
    {
        if (artificeDrawer == null)
        {
            artificeDrawer = new ArtificeDrawer();
            artificeDrawer.SetSerializedPropertyFilter(property => property.name != "m_Script");
        }

        scrollElement.contentContainer.Clear();
        SerializedObject serializedObject = new SerializedObject(activeObject);
        VisualElement activeTemplate = artificeDrawer.CreateInspectorGUI(serializedObject);
        scrollElement.Add(activeTemplate);
    }

    private void CreateNewAsset()
    {
        string newName = PromptForName();

        if (string.IsNullOrEmpty(newName))
        {
            Debug.LogWarning("Asset creation canceled or invalid name provided.");
            return;
        }

        T newAsset = CreateInstance<T>();

        string path = AssetDatabase.GenerateUniqueAssetPath($"{FolderPath}/{newName}.asset");

        AssetDatabase.CreateAsset(newAsset, path);
        AssetDatabase.SaveAssets();
        EditorUtility.FocusProjectWindow();
        Selection.activeObject = newAsset;
    }

    private void CreateAndLoadAsset()
    {
        string newName = PromptForName();

        if (string.IsNullOrEmpty(newName))
        {
            Debug.LogWarning("Asset creation canceled or invalid name provided.");
            return;
        }

        T newAsset = CreateInstance<T>();

        string path = AssetDatabase.GenerateUniqueAssetPath($"{FolderPath}/{newName}.asset");

        AssetDatabase.CreateAsset(newAsset, path);
        AssetDatabase.SaveAssets();
        EditorUtility.FocusProjectWindow();
        Selection.activeObject = newAsset;

        template = newAsset;
        objectField.value = template;
    }


    private string PromptForName()
    {
        return NameInputWindow.ShowWindow(typeof(T).Name);
    }

}
```
</details>



**Final Question: Can I achieve custom field order in the Unity Inspector?**  

**Problem:**  
With this inheritance structure:  
```csharp
public abstract class BaseEntity : ScriptableObject {
    public List<Stats> Stats;
}

public class Player : BaseEntity {
    public string name; // Inherited fields appear first
}
```  
Unity's default Inspector shows fields in declaration order:  
```
Stats
Name  
```  
But I want:  
```
Name
Stats  
```

**Proposed Solution:**  
Add a custom `[Sort]` attribute to control priority:  
```csharp
public abstract class BaseEntity : ScriptableObject {
    [Sort(2)] // Lower priority = appears later
    public List<Stats> Stats;
}

public class Player : BaseEntity {
    [Sort(1)] // Higher priority = appears first
    public string Name;
}
```  

**Implementation Attempt:**  
Modified Inspector GUI to sort properties:  
```csharp
public VisualElement CreateInspectorGUI(SerializedObject serializedObject) 
{
    // ... setup logic ...
    
    foreach (var property in serializedObject.GetIterator()
                                            .GetVisibleChildren()
                                            .SortProperties()) // Custom sorting extension
    {
        // ... property handling ...
    }
    
    // ... finalization ...
}
```  

Rustic approach :monkey_face:

```c#
public static List<SerializedProperty> SortProperties(this List<SerializedProperty> properties)
{
    return properties.OrderBy(p => 
    {
        Attribute[] attributes = p.GetAttributes();
        SortAttribute sortAttribute = attributes?.FirstOrDefault(attr => attr is SortAttribute) as SortAttribute;
        return sortAttribute?.Order ?? int.MaxValue;
    }).ToList();
}
```

**Questions:**  
1. Is this  sorting approach viable ?
2. Could this be implemented using Artificetoolkit utility methods (like those used for FoldoutGroup rendering) alongside a custom attribute?


Thanks for your time

**Comment by ZackPer** [comment]
Hello @exejutable 

I see what you did here. You decided to use the ArtificeDrawer in your editor window on demand, cool! I also love the fact that you examined the ArtificeDrawer code yourself. 

So your proposed solution for the [Sort] attribute is half way there. You actually need to apply this logic both to the CreateInspectorGUI and to the CreatePropertyGUI, since you would want the [Sort] attribute to work on children of serialized properties as well. Not only on the first layer of the SerializedObject.

Example were this is showcased:
```c#
public class TestScript : MonoBehaviour
{
    [Serializable]
    public class SubClass
    {
        [Sort(1)]
        public int firstInt;
        
        [Sort(0)]
        public int secondInt;
    }

    public SubClass subClassExample;
}
`

But you are exactly right, this is an easy to implement it to the artifice toolkit. We can do it when we find time, or if you want, you could be the first one to contribute to the code base and create a pull request! We will review it when you do.

What do you think?

**Comment by exejutable** [comment]
Hi @ZackPer ,

Hope you're doing well! I can work on the [Sort] attribute integration and want to make sure I set things up correctly. Quick questions:

Project Setup:
What’s the best way to clone/use the repo for testing?

1. Submodule inside a Unity project’s Assets/ folder?

`Fork → Branch → PR workflow?`

2. Testing:

Do you have a test scene or sample project, like the one in the readme examples?

3. Guidelines:

Any specific code style/docs I should follow? (e.g., naming, comments, or test coverage?)

No rush – just want to align with your workflow! Let me know your thoughts.

**Comment by ZackPer** [comment]
Hi @exejutable ,

Awesome to hear that you’re willing to contribute even more—thanks for your time!

Project Setup:
After cloning the repository and setting up your local environment, the best way to develop this project is by adding the package to a Unity testbed project (any empty or existing project will work). To do this, go to Window > Package Manager > Add package from disk. This ensures that all changes made to the toolkit are tracked as Git changes, allowing you to commit them when ready.

Testing & Contribution Workflow:
Yes, the Fork → Branch → PR workflow should work well for us. We do not yet have a sample project, maybe it will be something to consider in the future. We usually create a simple TestScript were we directly test any new feature.

Guidelines:
The ArtificeDrawer class serves as a good baseline for how we structure things. If anything stands out as not aligning with the project’s structure, we’ll review and address it in the PR.

Looking forward to your contribution!
